package errors

const (
	GodotenvDownloadErr      = "godotenv download error"
	ServerInitErr            = "server initial error"
	HashGenerateErr          = "hash generate error"
	VerifyPasswordErr        = "verify password error"
	IncorrectJsonBody        = "incorrect json body"
	IncorrectUserDataErr     = "incorrect user data error"
	InsufficientFundsErr     = "insufficient funds"
	InvalidDepositAmountErr  = "invalid deposit amount"
	UserCreateErr            = "user create error"
	InternalServerErr        = "internal server error"
	DataBaseConnectionErr    = "database connection error"
	DataBaseCloseErr         = "database close error"
	MigrationInitErrr        = "migration initial error"
	MigrationUpErr           = "migration up error"
	MigrationDropErr         = "nigration drop error"
	MigrationDownErr         = "nigration down error"
	MigrationCloserErr       = "migration close error"
	EmptyPasswordError       = "empty password error"
	UserSelectError          = "user select error"
	UserAlreadyExistErr      = "user already exist"
	SaveUserDBErr            = "database save user error"
	AdminAlreadyExistErr     = "superadmin already exist"
	IncorrectProductDataErr  = "incorrect product data"
	IncorrectProductPriceErr = "incorrect product price"
	TokenGenerateErr         = "token generate error"
	InvalidJsonBodyErr       = "invalid Json body error"
	UserDoesntExist          = "user doesnt exist"
	InvalidPasswordErr       = "invalid password"
)
